config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "static_pages/home"
    get "static_pages/help", as: "help"
    get "static_pages/about", as: "about"
    get "static_pages/contact", as: "contact"

    get "trends/index", as: "trends"

    namespace :admin do
      root "dashboard#index"

      patch "users/activate/:id", to: "block#update", as: "user_activate"
      patch "topics/activate/:id", to: "topics#activate", as: "topic_activate"
      patch "users/authorize/:id", to: "block#authorize", as: "user_authorize"
      get "posts/chart", to: "charts#post_new", as: "chart_post"
      get "users/chart", to: "charts#user_new", as: "chart_user"
      get "users/posts/chart", to: "charts#user_post", as: "chart_user_post"
      get "posts/:id/notify/:notification_id", to: "posts#show", as: "post_show_notify"
      get "users/export", to: "excels#index", as: "export_excel"
      get "posts/process/:id/:option", to: "posts#post_process", as: "posts_process"
      resources :users do
        resources :get_posts, only: :index
      end
      resource :check_posts, only: :update
      resources :posts do
        resources :get_reports, only: :index
      end
      resources :topics
    end

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      sessions: "admin/sessions",
      registrations: "admin/registers",
      passwords: "admin/passwords",
      confirmations: "admin/confirmations"
    }

    resources :users, except: %i(new create destroy) do
      resources :favorites, :activities, :followers, :followings, only: :index
    end

    resources :posts do
      resources :post_comments, only: :create
    end

    resources :post_comments, only: :create do
      resources :post_comments, only: :create
    end

    resources :topics, only: %i(index show)
    resources :post_marks, :post_likes,
        :user_topics, :relationships, only: %i(create destroy)
    resources :post_reports, only: :create
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: User.name
  belongs_to :followed, class_name: User.name,
    counter_cache: :follower_users_count

  validates :follower_id, :followed_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  authorize_resource

  before_action :find_user, only: %i(create destroy)

  def create
    current_user.follow @user
    check_follow_user

    respond_to :js
  end

  def destroy
    current_user.unfollow @user
    check_unfollow_user

    respond_to :js
  end

  private

  def find_user
    @user = User.find_by id: params[:user_id]
    return if @user

    @error = t ".not_found"
  end

  def check_follow_user
    @error = t ".unfollowed" unless current_user.following? @user
  end

  def check_unfollow_user
    @error = t ".followed" if current_user.following? @user
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
  def build_relationships
    current_user.active_relationships.build
  end

  def find_relationships user
    current_user.active_relationships.find_by followed_id: user.id
  end
end

app/views/relationships/create.js.erb
<% if @error.present? %>
  alert("<%= @error %>");
<% else %>
  $(".follow-user-<%= @user.id %>").html("<%= j render "users/unfollow", user: @user %>");
  $("#followings_count").html("<%= current_user.following.size %>");
  $("#followers-count-<%= @user.id %>").html("<%= I18n.t "users.user.followers_count", count: @user.followers.count %>");
  $("#relationship-followers").html("<%= j render "users/follower", follow_list: current_user.followers, path: user_followers_path(current_user) %>");
  $("#relationship-following").html("<%= j render "users/follower", follow_list: current_user.following, path: user_followings_path(current_user) %>");
<% end %>

app/views/relationships/destroy.js.erb
<% if @error.present? %>
  alert("<%= @error %>");
<% else %>
  $(".follow-user-<%= @user.id %>").html("<%= j render "users/follow", user: @user %>");
  $("#followings_count").html("<%= current_user.following.size %>");
  $("#followers-count-<%= @user.id %>").html("<%= I18n.t "users.user.followers_count", count: @user.followers.count %>");
  $("#relationship-followers").html("<%= j render "users/follower", follow_list: current_user.followers, path: user_followers_path(current_user) %>");
  $("#relationship-following").html("<%= j render "users/follower", follow_list: current_user.following, path: user_followings_path(current_user) %>");
<% end %>