config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "static_pages/home"
    get "static_pages/help", as: "help"
    get "static_pages/about", as: "about"
    get "static_pages/contact", as: "contact"

    get "trends/index", as: "trends"

    namespace :admin do
      root "dashboard#index"

      patch "users/activate/:id", to: "block#update", as: "user_activate"
      patch "topics/activate/:id", to: "topics#activate", as: "topic_activate"
      patch "users/authorize/:id", to: "block#authorize", as: "user_authorize"
      get "posts/chart", to: "charts#post_new", as: "chart_post"
      get "users/chart", to: "charts#user_new", as: "chart_user"
      get "users/posts/chart", to: "charts#user_post", as: "chart_user_post"
      get "posts/:id/notify/:notification_id", to: "posts#show", as: "post_show_notify"
      get "users/export", to: "excels#index", as: "export_excel"
      get "posts/process/:id/:option", to: "posts#post_process", as: "posts_process"
      resources :users do
        resources :get_posts, only: :index
      end
      resource :check_posts, only: :update
      resources :posts do
        resources :get_reports, only: :index
      end
      resources :topics
    end

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      sessions: "admin/sessions",
      registrations: "admin/registers",
      passwords: "admin/passwords",
      confirmations: "admin/confirmations"
    }

    resources :users, except: %i(new create destroy) do
      resources :favorites, :activities, :followers, :followings, only: :index
    end

    resources :posts do
      resources :post_comments, only: :create
    end

    resources :post_comments, only: :create do
      resources :post_comments, only: :create
    end

    resources :topics, only: %i(index show)
    resources :post_marks, :post_likes,
        :user_topics, :relationships, only: %i(create destroy)
    resources :post_reports, only: :create
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  TOPIC_PARAMS = %i(name status).freeze

  enum status: {off: 0, on: 1}

  has_many :posts, dependent: :destroy

  has_many :user_topics, dependent: :destroy
  has_many :users, through: :user_topics

  validates :name, presence: true,
    length: {maximum: Settings.topic.validates.name_topic},
    uniqueness: {case_sensitive: true}

  scope :order_created_at, ->{order created_at: :desc}
  scope :order_by_user, (lambda do
    topic_count = UserTopic
      .group(:topic_id)
      .select(:topic_id, "count(topic_id) as num")

    joins("LEFT JOIN (#{topic_count.to_sql}) as topic_count
      ON topic_count.topic_id = id")
    .order("topic_count.num desc")
  end)
  scope :by_topic_name, (lambda do |name|
    where("name like ?", "%#{name}%") if name.present?
  end)
  scope :order_name, ->{order name: :asc}
  scope :order_topics_count, ->{order user_topics_count: :desc}
  scope :not_followers, (lambda do |user|
    where.not(id: user.topic_ids)
  end)

  class << self
    def sort_type sort
      if sort.eql? "created_at"
        order_created_at
      elsif sort.eql? "alphabet"
        order_name
      elsif sort.eql? "followers"
        order_topics_count
      else
        all
      end
    end

    def by_follow_status status, user
      if status.eql? "on"
        user.topics
      elsif status.eql? "off"
        not_followers(user)
      else
        all
      end
    end
  end
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < AdminController
  before_action :authenticate_user!

  before_action :load_topic, except: %i(index new create)

  add_breadcrumb I18n.t("topic.breadcrumbs.list"), :admin_topics_path

  def index
    @topics = Topic.order_created_at.page(params[:page]).per Settings.post.page
  end

  def new
    add_breadcrumb I18n.t("topic.breadcrumbs.new")
    @topic = Topic.new
  end

  def create
    @topic = Topic.new topic_params
    if @topic.save
      flash[:notice] = t "topic.controller.create_success"
      redirect_to admin_topics_path
    else
      flash.now[:alert] = t "topic.controller.create_failed"
      render :new
    end
  end

  def edit
    add_breadcrumb I18n.t("topic.breadcrumbs.edit")
  end

  def update
    if @topic.update topic_params
      flash[:notice] = t "users.update.success"
      redirect_to admin_topics_path
    else
      flash[:alert] = t "users.update.fail"
      render :edit
    end
  end

  def destroy
    if @topic.destroy
      flash[:notice] = t "topic.controller.deleted_success"
    else
      flash.now[:alert] = t "topic.controller.deleted_error"
    end
    redirect_to admin_topics_path
  end

  def activate
    if @topic.on?
      flash[:notice] = t "topic.controller.activate_success"
      @topic.off!
    else
      flash.now[:alert] = t "topic.controller.activate_error"
      @topic.on!
    end
    redirect_to admin_topics_path
  end

  private

  def topic_params
    params.require(:topic).permit Topic::TOPIC_PARAMS
  end

  def load_topic
    @topic = Topic.find_by id: params[:id]
    return if @topic

    flash[:alert] = t "topic.controller.not_found"
    redirect_to admin_topics_path
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!

  authorize_resource Topic

  before_action :find_topic, only: :show

  def index
    @topics = Topic.by_topic_name(params[:name])
                   .sort_type(params[:select_type])
                   .by_follow_status(params[:status], current_user)
                   .page(params[:page])
                   .per Settings.topics.per_page
  end

  def show
    @posts = @topic.posts
                   .on
                   .includes(:user, :tags, :post_marks)
                   .order_created_at
  end

  private

  def find_topic
    @topic = Topic.find_by id: params[:id]
    return if @topic

    flash[:alert] = t ".not_found"
    redirect_to root_url
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def topic_status status
    if status
      {
        css: Settings.status.on_status,
        status: t("post.index.on_status")
      }
    else
      {
        css: Settings.status.off_status,
        status: t("post.index.off_status")
      }
    end
  end
end

app/views/admin/topics/_colums.html.erb
<tr>
  <td><%= t "topic.index.name" %></td>
  <td><%= t "topic.index.created_at" %></td>
  <td><%= t "topic.index.status" %></td>
  <td><%= t "topic.index.action" %></td>
</tr>

app/views/admin/topics/_form.html.erb
<%= form_for [:admin, @topic] do |f| %>
  <div class="row p-3">
     <div class="form-group">
      <%= f.label t "post.new.title" %>
      <%= f.text_field :name, class: "form-control", placeholder: t("post.new.title") %>
      <%= display_error f.object, :name %>
     </div>
  </div>
  <div class="card-body">
    <div class="form-group">
      <%= f.label t "post.new.status" %>
      <%= f.check_box :status, {checked: true}, :on, :off %>
    </div>
  </div>
  <div class="card-footer">
    <%= f.submit t("post.new.create"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/topics/_topic.html.erb
<tr>
  <td><%= topic.name %></td>
  <td><%= topic.created_at %></td>
  <td>
    <div class="status <%= topic_status(topic.on?)[:css] %>">
      <span>
        <%= topic_status(topic.on?)[:status] %>
      </span>
    </div>
  </td>
  <td>
    <%= link_to edit_admin_topic_path topic.id, class: "nav-link active d-inline" do %>
      <i class="fas fa-edit nav-icon text-success"></i>
    <% end %>
    <%= link_to admin_topic_activate_path(topic.id), method: :patch, class: "nav-link active d-inline" do %>
      <% if topic.on? %>
        <i class="fas fa-lock-open nav-icon text-warning"></i>
      <% else %>
        <i class="fas fa-lock nav-icon text-warning"></i>
      <% end %>
    <% end %>
    <%= link_to admin_topic_path(topic.id), method: :delete,
      data: { confirm: t("users.index.confirm_delete") },
      class: "nav-link active d-inline" do %>
      <i class="fas fa-trash-alt nav-icon text-danger"></i>
    <% end %>
  </td>
</tr>

app/views/admin/topics/edit.html.erb
<div class="card card-primary">
  <div class="card-header">
    <h3 class="card-title"><%= t "post.new.post" %></h3>
  </div>
  <%= render "form" %>
</div>

app/views/admin/topics/index.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="card-title"><%= t "topic.index.title" %></h3>
  </div>
  <div class="card-body">
    <table id="example1" class="table table-bordered table-striped">
      <div class="input-group input-group-sm">
        <label><%= t "post.index.post_numbers" %><%= t "topic.index.count", count: @topics.total_count %></label>
        <%= link_to new_admin_topic_path,
          class: "nav-link active d-inline mb-3 p-0 pl-3" do %>
          <i class="fas fa-plus nav-icon text-success"></i>
        <% end %>
      </div>
      <thead>
        <%= render "colums" %>
      </thead>
      <tbody>
        <%= render @topics %>
      </tbody>
      <tfoot>
        <%= render "colums" %>
      </tfoot>
    </table>
  </div>
</div>
<%= paginate @topics, theme: Settings.theme.name_bootstrap %>

app/views/admin/topics/new.html.erb
<div class="card card-primary">
  <div class="card-header">
    <h3 class="card-title"><%= t "topic.new.title" %></h3>
  </div>
  <%= render "form" %>
</div>