config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "static_pages/home"
    get "static_pages/help", as: "help"
    get "static_pages/about", as: "about"
    get "static_pages/contact", as: "contact"

    get "trends/index", as: "trends"

    namespace :admin do
      root "dashboard#index"

      patch "users/activate/:id", to: "block#update", as: "user_activate"
      patch "topics/activate/:id", to: "topics#activate", as: "topic_activate"
      patch "users/authorize/:id", to: "block#authorize", as: "user_authorize"
      get "posts/chart", to: "charts#post_new", as: "chart_post"
      get "users/chart", to: "charts#user_new", as: "chart_user"
      get "users/posts/chart", to: "charts#user_post", as: "chart_user_post"
      get "posts/:id/notify/:notification_id", to: "posts#show", as: "post_show_notify"
      get "users/export", to: "excels#index", as: "export_excel"
      get "posts/process/:id/:option", to: "posts#post_process", as: "posts_process"
      resources :users do
        resources :get_posts, only: :index
      end
      resource :check_posts, only: :update
      resources :posts do
        resources :get_reports, only: :index
      end
      resources :topics
    end

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      sessions: "admin/sessions",
      registrations: "admin/registers",
      passwords: "admin/passwords",
      confirmations: "admin/confirmations"
    }

    resources :users, except: %i(new create destroy) do
      resources :favorites, :activities, :followers, :followings, only: :index
    end

    resources :posts do
      resources :post_comments, only: :create
    end

    resources :post_comments, only: :create do
      resources :post_comments, only: :create
    end

    resources :topics, only: %i(index show)
    resources :post_marks, :post_likes,
        :user_topics, :relationships, only: %i(create destroy)
    resources :post_reports, only: :create
  end
end

app/views/layouts/admin/_content_header.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark"><%= t "dashboard.content.page" %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <%= render_breadcrumbs :separator => " / " %>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin/_footer.html.erb
<footer class="main-footer">
  <div class="float-right d-none d-sm-inline">
    <%= t "dashboard.footer.title" %>
  </div>
  <strong><%= t "dashboard.footer.copy" %></strong> <%= t "dashboard.footer.right" %>
</footer>

app/views/layouts/admin/_header.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to "#", :class => "nav-link", :role => "button", "data-widget" => "pushmenu" do %>
        <i class="fa fa-bars"></i>
      <% end %>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to t("dashboard.header.home"), admin_root_path, class: "nav-link" %>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to t("dashboard.header.contact"), "#", class: "nav-link" %>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown">
      <%= link_to "#", class: "nav-link", "data-toggle" => "dropdown" do %>
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge" id="notifynumber">
          <%= get_uncheck_notification %>
        </span>
      <% end %>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" id="notification">
        <%= render get_all_notification %>
      </div>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to t("layouts.application.logout"), destroy_user_session_path,
        method: :delete, class: "nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/admin/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "admin/admin", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_pack_tag "admin/admin", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag Ckeditor.cdn_url %>
<%= yield :javascript_includes %>

app/views/layouts/admin/_sidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <%= link_to "#", class: "brand-link" do %>
    <%= image_tag "/img/AdminLTELogo.png", class: "brand-image img-circle elevation-3", alt: "logo" %>
    <span class="brand-text font-weight-light"><%= t "dashboard.sidebar.title" %></span>
  <% end %>
  <div class="sidebar">
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <%= load_user_avatar current_user %>
      </div>
      <div class="info">
        <%= link_to current_user.name, admin_user_path(current_user.id), class: "d-block" %>
      </div>
      <%= hidden_field(:current_user, :id) %>
    </div>
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <%= link_to root_path, class: "nav-link" do %>
            <i class="nav-icon fas fa-home"></i>
            <p>
              <%= t "dashboard.sidebar.page" %>
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_root_path, class: "nav-link" do %>
            <i class="nav-icon fab fa-instagram"></i>
            <p>
              <%= t "dashboard.sidebar.dashboard" %>
            </p>
          <% end %>
        </li>
        <li class="nav-item has-treeview">
          <%= link_to "#", class: "nav-link" do %>
            <i class="nav-icon fas fa-user"></i>
            <p>
              <%= t "dashboard.sidebar.user" %>
              <i class="right fas fa-angle-left"></i>
            </p>
          <% end %>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <%= link_to admin_user_path(current_user.id), class: "nav-link" do %>
                <i class="fas fa-address-card nav-icon"></i>
                <p><%= t "dashboard.sidebar.profile" %></p>
              <% end %>            </li>
            <li class="nav-item">
              <%= link_to admin_users_path, class: "nav-link" do %>
                <i class="fas fa-users nav-icon"></i>
                <p><%= t "dashboard.sidebar.list" %></p>
              <% end %>
            </li>
          </ul>
        </li>
        <li class="nav-item has-treeview">
          <%= link_to "#", class: "nav-link" do %>
            <i class="nav-icon fas fa-newspaper"></i>
            <p>
              <%= t "dashboard.sidebar.post" %>
              <i class="right fas fa-angle-left"></i>
            </p>
          <% end %>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <%= link_to admin_posts_path, class: "nav-link" do %>
                <i class="fas fa-list-ul nav-icon"></i>
                <p><%= t "dashboard.sidebar.list" %></p>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_admin_post_path, class: "nav-link" do %>
                <i class="fas fa-plus nav-icon"></i>
                <p><%= t "dashboard.sidebar.add" %></p>
              <% end %>
            </li>
          </ul>
        </li>
        <li class="nav-item has-treeview">
          <%= link_to "#", class: "nav-link" do %>
            <i class="nav-icon fas fa-book"></i>
            <p>
              <%= t "dashboard.sidebar.topic" %>
              <i class="right fas fa-angle-left"></i>
            </p>
          <% end %>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <%= link_to admin_topics_path, class: "nav-link" do %>
                <i class="fas fa-list-ul nav-icon"></i>
                <p><%= t "dashboard.sidebar.list" %></p>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_admin_topic_path, class: "nav-link" do %>
                <i class="fas fa-plus nav-icon"></i>
                <p><%= t "dashboard.sidebar.add" %></p>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</aside>
<aside class="control-sidebar control-sidebar-dark">
  <div class="p-3">
    <h5><%= t "dashboard.sidebar.title" %></h5>
    <p><%= t "dashboard.sidebar.sidebar_content" %></p>
  </div>
</aside>